# Generated by Django 3.1.7 on 2021-04-05 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.TextField()),
                ('img', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('portrayed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_season', models.IntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.character')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('episode', models.IntegerField()),
                ('air_date', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.season')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.ManyToManyField(to='series.Serie'),
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(to='series.Episode'),
        ),
        migrations.AddField(
            model_name='character',
            name='seasons',
            field=models.ManyToManyField(to='series.Season'),
        ),
    ]
