# Generated by Django 3.2 on 2021-05-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default=None, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=None, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=None, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField(default=0)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.artist'),
        ),
    ]
